Cargo.toml
README.md
book/src/merkletree.md
rust-toolchain.toml
src/lib.rs
src/merkletree.rs

Add initial MerkleTree implementation, which is a wrapper on top of Plonky2's MerkleTree, with the idea that the future iteration will replace it by the MerkleTree specified at
https://0xparc.github.io/pod2/merkletree.html .
This PR relates to #6 .
Notes:
- initially we mentioned about doing a 'fake merkletree' where it would be an interface which internally just does hashes of the keyvalues, where a 'merkleproof' would be just the entire keyvalues so that the verifier takes it all and hashes it to check that the specific keyvalue is there. But after checking the Plonky2 existing merkletree, seemed more straightforward (and more close to our final merkletree) to just use it
- currently it does not implement the non-inclusion proofs, which in this version are just mock functions. This is, …

add initial MerkleTree implementation

---

src/backend.rs
src/backends/mock_signed.rs
src/frontend.rs
src/merkletree.rs
src/middleware.rs

Just moved the logic of calculating the id of a signed pod into the MockSignedPod.
Also updated the SignedPod, MainPod traits to return Result on the sign/prove operations.

feat: integrate mt in mock_sign

---

src/backends/mock_main.rs
src/frontend.rs
src/middleware.rs

Compute MainPod.id from pub_statements hash; for it, introduce the trait `ToFields` at the middleware and implement it for the Statement related types.

compute MainPod.id from pub_statements; and introduce the trait `ToFields`

---

src/backends/mock_main.rs
src/examples.rs
src/frontend.rs

- after brief discussion with aard, we decided adding at least some of the POD1 types to POD2 would make sense
- starting with a `bool` atomic type to POD2 since it is a valid JSON type
- added a brief test with a 'ticket' signed pod and a main pod that proves some things about the ticket

feat: add new bool frontend type

---

src/backends/mock_main.rs
src/backends/mock_main/operation.rs
src/backends/mock_main/statement.rs
src/backends/mock_signed.rs
src/examples.rs
src/frontend.rs
src/frontend/operation.rs
src/frontend/statement.rs
src/middleware/mod.rs
src/middleware/operation.rs
src/middleware/statement.rs

chore: enums for statement and op types

---

src/backends/mock_main/mod.rs
src/frontend/custom.rs
src/frontend/mod.rs
src/middleware/custom.rs
src/middleware/mod.rs

- migrate middleware::custom::tests types and structs to frontend::custom, adapt it and add comments detailing logic
- simplify custom predicate's frontend interfaces, making it less verbose to define Statement Template arguments
The main idea is that when defining the arguments at a statement template, it can be done from 3 different inputs:
i. `(&str, literal)`: this is to set a POD and a field, ie. `(POD, literal("field")`)
ii. `(&str, &str)`: this is to define a origin-key wildcard pair, ie. `(src_origin, src_dest)`
iii. `Value`: this is to define a literal value, ie. `0`
(this is [documented in the code](https://github.com/0xPARC/pod2/blob/22a309b285e324585375adcb2556e8930fef2cf8/src/frontend/custom.rs#L33), and it's usage can be seen at [the frontend::custom …

Frontend: simplify custom predicates interfaces

---

src/backends/mock_main/statement.rs
src/frontend/custom.rs
src/frontend/mod.rs
src/middleware/custom.rs
src/middleware/operation.rs
src/middleware/statement.rs

feat: partial incorporation of custom predicates into statement and operation structures in middleware

---

.github/workflows/typos.toml
src/backends/mock_main/mod.rs
src/backends/mock_main/statement.rs
src/frontend/custom.rs
src/frontend/mod.rs
src/middleware/custom.rs
src/middleware/mod.rs
src/middleware/statement.rs

This resolves #75 
Please take a look at my code and give me pointers for coding style.
- I include `params` as an input to `to_fields` so that `to_fields` can pad everything to a fixed length.  I think we have to do this because eventually when we do everything in-circuit, we're going to need to be able to find everything at a constant offset.  Is there a better way to deal with this issue?
- All my `to_fields()` implementations chain together a bunch of vectors, my code is ugly, please suggest more idiomatic Rust.

Serialize and hash custom predicates

---

.github/workflows/typos.toml
src/backends/plonky2/mock_main/mod.rs
src/backends/plonky2/mock_main/operation.rs
src/frontend/custom.rs
src/frontend/mod.rs
src/frontend/operation.rs
src/frontend/statement.rs
src/middleware/operation.rs

feat: custom predicates in frontend statement and operation types

---

src/backends/plonky2/mock_main/mod.rs
src/frontend/custom.rs
src/frontend/operation.rs
src/middleware/custom.rs
src/middleware/mod.rs
src/middleware/operation.rs

- add constructor method for CustomPredicate
- make size checks at the CustomPredicate creation, so that once instantiated we can assume that contains valid data
This resolves #79

limit the number of StatementTmpl in CustomPredicate:

---

src/backends/plonky2/basetypes.rs

The conversion of `Value` types to `i64` seems to be buggy. I've written a test of round-trip conversions which fails in the first commit, and then made a fix which causes the test to pass in the second.

Fix i64 conversion

---

src/backends/plonky2/basetypes.rs
src/middleware/custom.rs

Fix a couple of locations in the custom predicate serialization where 4 wasn't changed to the general HASH_SIZE before

Replace constant 4 with HASH_SIZE

---

src/examples.rs
src/frontend/mod.rs

chore: wrap up ETHDoS example

---

src/backends/counter.rs
src/backends/mod.rs
src/backends/plonky2/basetypes.rs
src/backends/plonky2/primitives/merkletree.rs

Currently counts hashes, tree insertions and tree proof generations. We can extend it to also count the POD operations or other kind of logic that we might want to count.
On the direction of #118 .

add initial counter setup

---

src/examples.rs
src/frontend/mod.rs
src/frontend/operation.rs

This PR exposes the frontend constant-introducing mechanism as a MainPod builder method (`pub_literal`/`priv_literal`) and rounds out the ops exposed via the `op!` macro. These make the ETHDoS example less unwieldy and have been incorporated into it.

chore(frontend): expose literal method in MainPod builder + more op macros

---

book/src/merkletree.md
src/backends/plonky2/basetypes.rs
src/backends/plonky2/mock_signed.rs
src/backends/plonky2/primitives/merkletree.rs
src/backends/plonky2/primitives/merkletree_circuit.rs
src/backends/plonky2/primitives/mod.rs
src/middleware/basetypes.rs
src/middleware/containers.rs
src/middleware/mod.rs

This PR implements the plonky2 circuit that verifies the merkleproof of existance and merkleproof of non-existence described at #124 and in [docs/merkletree](https://0xparc.github.io/pod2/merkletree.html#proofs-of-inclusion-and-non-inclusion).
This PR resolves #124 and unblocks starting to work on #133.

Merkleproof verify circuit

---

src/backends/plonky2/common.rs
src/backends/plonky2/main.rs
src/backends/plonky2/mock_main/mod.rs
src/backends/plonky2/mock_main/operation.rs
src/backends/plonky2/mock_main/statement.rs
src/backends/plonky2/primitives/merkletree_circuit.rs
src/frontend/mod.rs
src/middleware/custom.rs
src/middleware/mod.rs
src/middleware/operation.rs
src/middleware/statement.rs

I've implemented the necessary `ToFields` for `Operation` for the MainPod circuit.
I've fixed a few things, implemented the witness assignment for Statements and Operations and added two tests:
- SignedPod verification circuit test
- Operation verification circuit test, only for the None operation for now, but it should be easy to follow the pattern to add a test for each operation.
I've also did a small refactor on the MerkleTree circuit to follow the same naming conventions as the MainPod circuit gates.  I've also moved the max depth from a generic constant to a dynamic parameter in Params.

Progress on the MainPod circuit

---

src/backends/plonky2/circuits/mainpod.rs
src/backends/plonky2/primitives/merkletree.rs
src/backends/plonky2/primitives/merkletree_circuit.rs
src/backends/plonky2/primitives/mod.rs
src/backends/plonky2/primitives/signature.rs
src/backends/plonky2/primitives/signature_circuit.rs
src/middleware/mod.rs

This PR implements the `SignatureVerifyGadget`, the circuit that verifies the `Signature`; where since the signatures currently are proof-based signatures, the `SignatureVerifyGadget` internally is doing a 1-level recursive proof verification.

add circuit to verify signatures (SignatureVerifyGadget)

---

book/src/examples.md
book/src/operations.md
book/src/statements.md

Document the missing parts of the full ZuKYC example.
This requires defining the `Hash` native predicate and `HashOf` native operation.
The public key derivation is just a hash following the current spec of our signature scheme.  This will change to something more complex if we change the signature scheme, and in that case I think we should rely on an introductory gadget for the key derivation.
I've defined the Hash as taking 2 values so that we can create chains to absorb data of dynamic size.

complete full zukyc example doc

---

src/backends/plonky2/circuits/common.rs
src/backends/plonky2/circuits/mainpod.rs
src/backends/plonky2/mainpod.rs
src/backends/plonky2/mock/mainpod/mod.rs
src/backends/plonky2/mock/mainpod/operation.rs
src/backends/plonky2/primitives/merkletree.rs
src/backends/plonky2/primitives/merkletree_circuit.rs
src/middleware/mod.rs
src/middleware/operation.rs
src/middleware/statement.rs

chore(backend): implement more circuit op logic

---

src/examples/custom.rs
src/examples/mod.rs
src/frontend/custom.rs
src/frontend/mod.rs
src/frontend/operation.rs
src/frontend/serialization.rs
src/frontend/statement.rs
src/middleware/statement.rs

Closes #161 
In order to allow for serialization of front-end versions of Custom Statements, it's necessary to include the definition of the matching Custom Deduction. This PR adds front-end types for custom predicate definitions, including statement templates.
Unfortunately this leads to some duplication of code already implemented in the middleware, for example for wildcard matching. This is needed in the front-end for `MainPodBuilder`, but the compiler also needs a version of the same thing for `Operation::check`. It's not a _huge_ amount of code, but there is some risk that we change how the middleware works without changing how the front-end works, or vice versa. If we're intending to do a larger tidy-up of the code later then maybe we can decide what to do about this then.

Add extra front-end types and make MainPodBuilder emit these

---

rust-analyzer.toml

This PR adds a `rust-analyzer.toml` which defaults to absolute imports in LSP-capable editors.

chore(qol): add rust-analyzer.toml

---

src/examples/mod.rs

Rather than using a hard-coded value, use the argument passed to the `zu_kyc_sign_pod_builders`, which was previously being ignored.

Use the sanctions set passed in as arg to builder function

---

src/backends/plonky2/circuits/mainpod.rs
src/backends/plonky2/circuits/signedpod.rs
src/backends/plonky2/mainpod/mod.rs
src/backends/plonky2/mainpod/operation.rs
src/backends/plonky2/primitives/merkletree.rs
src/backends/plonky2/primitives/merkletree_circuit.rs
src/backends/plonky2/primitives/signature_circuit.rs

Resolve https://github.com/0xPARC/pod2/issues/183 with a twist
The issue was about processing the witness outside of the `set_target` method, and that processing includes padding.  Part of this change was already started in https://github.com/0xPARC/pod2/pull/196
My original arguments for this pattern were:
- Make the code around the circuit as simple and transparent as possible so that we focus on the constraint logic
- Allow writing tests that use `set_targets` and directly set all the witness values
But once I started applying this pattern in the MainCircuit I noticed some issues.  Here are my counter arguments:
- The code looks more clean by doing the padding inside `set_targets` because it allows reusing existing types as arguments to `set_targets` (and those types are not yet …

Padding in set target

---

Cargo.toml
src/backends/plonky2/mainpod/operation.rs
src/backends/plonky2/mainpod/statement.rs
src/backends/plonky2/mock/mainpod.rs
src/backends/plonky2/mock/signedpod.rs
src/backends/plonky2/primitives/merkletree.rs
src/frontend/custom.rs
src/frontend/mod.rs
src/frontend/operation.rs
src/frontend/serialization.rs
src/middleware/basetypes.rs
src/middleware/containers.rs
src/middleware/custom.rs
src/middleware/mod.rs
src/middleware/operation.rs
src/middleware/serialization.rs
src/middleware/statement.rs

Closes #195 
Re-implements serialization based on the new refactored code.
Serialization format should be pretty similar to how it was before, with some small cosmetic changes.
I've had to implement a few more custom serialization functions, in order to avoid serializing middleware data. I've commented in the places where this was necessary, so that we can be aware that those custom serialization functions will not automatically track changes to the types in the way that Serde's attribute-based serialization does.
The new version has more tests, and in particular has an end-to-end test which:
- Serializes a SignedPod, and two quite different MainPods
- Generates JSON Schemas for SignedPod and MainPod
- Tests that the real SignedPod and MainPods can be validated at runtime using the …

Re-implement serialization

---

src/backends/plonky2/circuits/signedpod.rs
src/backends/plonky2/mainpod/mod.rs
src/backends/plonky2/mock/mainpod.rs
src/backends/plonky2/mock/signedpod.rs
src/backends/plonky2/signedpod.rs
src/lib.rs
src/middleware/mod.rs

This commit makes Pod inherit Any, which removes the need for the as_any and into_any functions.
It requires the `trait_upcasting` feature, which was considered experimental in the `nightly-2025-01-20` toolchain, but has since been stabilized: https://github.com/rust-lang/rust/issues/65991

make Pod derive from Any

---

src/backends/plonky2/basetypes.rs
src/backends/plonky2/mainpod/mod.rs

This PR makes the Plonky2 config in use more explicit, making it easier to swap out the extension degree and field for another in testing.

chore(backend): make Plonky2 config more explicit

---

book/src/values.md
src/frontend/custom.rs
src/frontend/mod.rs
src/middleware/containers.rs

Closes #224 
This adds desugaring of statement templates during the building of a custom predicate. `Gt` and `GtEq` are replaced by `Lt` and `LtEq` respectively, `DictContains`/`ArrayContains` are replaced by `Contains`, and `DictNotContains`/`SetNotContains` are replaced by `NotContains`.
~~`SetContains` is TODO because it's not immediately obvious how the third argument to `Contains` should be generated.~~ EDIT: `SetContains` is now implemented, including a change in the Set implementation: instead of building the Set Merkle tree from pairs of `value` and `EMPTY_VALUE`, we now duplicate the `value`. This makes the `Contains` statement derived from `SetContains` deterministic.

Desugar statement templates

---

src/backends/plonky2/mainpod/mod.rs
src/backends/plonky2/mock/mainpod.rs
src/backends/plonky2/mock/signedpod.rs
src/backends/plonky2/primitives/signature/mod.rs
src/backends/plonky2/signedpod.rs
src/frontend/mod.rs
src/frontend/serialization.rs
src/middleware/mod.rs

This PR adds serialization for the plonky2 variants of Signed and Main PODs.
Both mock and plonky2 PODs have identical signed representations. In Signed PODs, the `signature` field is an opaque string, and in Main PODs the `proof` field is an opaque string. External applications should not rely on this string having any particular contents or structure.
See the `SerializedSignedPod` and `SerializedMainPod` types - these are intermediate types used to standardize the representation before serialization.

Serialization for Plonky2 Signed and Main PODs

---

.github/workflows/typos.toml
Cargo.toml
src/backends/plonky2/mod.rs
src/backends/plonky2/recursion/circuit.rs
src/backends/plonky2/recursion/mod.rs

The RecursiveCircuit verifies N proofs (N=arity), together with the logic defined at the InnerCircuit (in our case, used for the MainPodCircuit logic).
The arity defines the maximum amount of proofs that the RecursiveCircuit verifies. When arity>1, using the RecursiveCircuit has the shape of a tree of the same arity.
The recursive circuit can verify proofs of other circuits other than itself, as long as the common_data & config are the same.
resolves #174

Add RecursiveCircuit

---

.github/workflows/build.yml
src/backends/plonky2/circuits/mainpod.rs
src/backends/plonky2/circuits/metrics.rs
src/backends/plonky2/mainpod/mod.rs
src/examples/custom.rs
src/examples/mod.rs
src/frontend/custom.rs
src/middleware/custom.rs
src/middleware/operation.rs

Resolve #239 
I've managed to implement this feature with virtually no extra cost in the circuit by encoding the case `anchored_key.pod_id = SELF` in a statement template as a wildcard at index 0, and adding an offset +1 to regular wildcard indexes.  Then in the circuit the array of custom predicate arguments starts with a constant value of `SELF`, so resolving the wildcard index 0 returns `SELF`.  Since the random access in plonky2 has a fixed cost for any array up to 64 elements, and the number of arguments will always be much smaller than 64 the total number of constraints after this change is unaffected.
I've rewritten the ethdos to use `SELF` which allows the reductions described in the issue.  Now we can adjust the minimum parameters of a MainPod for ethdos which reduce the number …

allow SELF in st_tmpl

---

src/backends/plonky2/circuits/mainpod.rs
src/backends/plonky2/mainpod/mod.rs
src/backends/plonky2/mock/mainpod.rs
src/examples/mod.rs
src/frontend/mod.rs
src/middleware/mod.rs

The MainPod id is now calculated with front padding and a fixed size independent of max_public_statements so that introduction gadgets can be verified by a MainPod while paying only for the number of statements they use.  This is because with front padding of none-statements we can precompute the poseidon state corresponding to absorbing all the padding statements and only pay constraints for the non-padding statements.
The id is calculated as follows:
`id = hash(serialize(reverse(statements || none-statements)))`
I introduced a new parameter `num_public_statements_id` which allows making differently-sized statement to id compatible.

calculate MainPod id in a dynamic-friendly way

---

book/src/merklestatements.md
src/backends/plonky2/error.rs
src/backends/plonky2/mainpod/mod.rs
src/backends/plonky2/recursion/circuit.rs
src/frontend/mod.rs
src/frontend/operation.rs

- expose some interfaces for external usage (from introduction-pods)
- add From<MainPod> for OperationArg, add copy op!

expose some interfaces for external usage (from introduction-pods)

---

src/backends/plonky2/primitives/ec/curve.rs

chore(backend): add flags to PointTarget struct

---

src/backends/plonky2/basetypes.rs
src/backends/plonky2/circuits/common.rs
src/backends/plonky2/circuits/mainpod.rs
src/backends/plonky2/circuits/signedpod.rs
src/backends/plonky2/emptypod.rs
src/backends/plonky2/mainpod/mod.rs
src/backends/plonky2/mock/mainpod.rs
src/backends/plonky2/mock/signedpod.rs
src/backends/plonky2/primitives/merkletree/circuit.rs
src/backends/plonky2/signedpod.rs
src/examples/mod.rs
src/frontend/custom.rs
src/frontend/mod.rs
src/frontend/serialization.rs
src/lang/processor.rs
src/middleware/containers.rs
src/middleware/mod.rs

When generating a MainPod, the circuit checks that the used verifier_datas for the verification of the recursive proofs, appear in the set of allowed verifier_datas (which is a `containers::Set`, a merkletree).
- Add `VDSet` construction
- Add `VDSet` proofs verification in the MainPod's circuit
- update containers (`Dictionary`, `Set`, `Array`)
- get rid of usage of the global constant `MAX_DEPTH` in most of places except for 3 locations, opened the issue #273 describing it.
This PR should resolve #249 , resolve #250.

Add verifier-datas tree (set) & in-circuit verification

---

Cargo.toml
examples/signed_pod.rs
src/backends/plonky2/primitives/ec/curve.rs
src/backends/plonky2/signedpod.rs
src/middleware/mod.rs

Depends on #304 
Implement Display for Point like this:
- In alternate mode, show the `x`, `u` coordinates using the display of the extension field
- In normal mode if the point is in the subgroup display the `u` coord in base58.  If not in the subgrup display the `x` and `u` coords concatenated in base58. 
Implement the serialization/deserialization using the base58 encoding.
The reason to use base58 VS base64 is to make it easier to select an entire public key and make it easy to compare two public keys or even read them aloud.

Display point in base58

---

src/backends/plonky2/basetypes.rs
src/backends/plonky2/emptypod.rs
src/backends/plonky2/mainpod/mod.rs
src/backends/plonky2/mainpod/statement.rs
src/backends/plonky2/mock/emptypod.rs
src/backends/plonky2/mock/mainpod.rs
src/backends/plonky2/mock/signedpod.rs
src/backends/plonky2/primitives/ec/schnorr.rs
src/backends/plonky2/signedpod.rs
src/middleware/mod.rs

add eq & partial_eq for RecursivePod, Pod traits and VDSet struct.
(this is in order to be able to check parsed data structs in the introduction-pods, but probably useful in other use cases where we need to compare PODs)

add eq & partial_eq for RecursivePod, Pod traits and VDSet struct (for usage from introduction-pods)

---

src/backends/plonky2/mainpod/mod.rs
src/middleware/containers.rs

Resolves #308.
This is a short-term fix to unblock other workstreams. While there is nothing strictly wrong with it, it will yield larger than usual Merkle tree depths for certain sets.

fix: use raw values for container keys and values

---

src/frontend/serialization.rs

Closes #310 
This reintroduces the `public_statements` and `entries` fields for `SerializedMainPod` and `SerializedSignedPod` respectively. This allows us to generate meaningful JSON Schemas that tell third-party (non-Rust) clients what data they can find in the serialization format.
This does introduce a smaller problem: there is now duplication of data between the typed `entries`/`public_statements` field and the untyped `data` blob, which includes its own copies of that data. However, this is less bad than not having any meaningful schema for our serialization format.

Restore typed data to serialized PODs

---

src/backends/plonky2/primitives/ec/curve.rs
src/lang/grammar.pest
src/lang/mod.rs
src/lang/parser.rs
src/lang/processor.rs
src/middleware/basetypes.rs
src/middleware/mod.rs

Closes #299 
PublicKeys can now be expressed as Podlang literals:
```
PublicKey(base58string)
```
I've also tidied up the handling of PodId vs Raw. Now, any bare hex string (0x-prefixed) is interpreted as a PodId, unless wrapped in `Raw()`, in which case it will be interpreted as a `RawValue`.
I'm open to changing these if the wrappers seem too verbose. For instance, maybe we could use a special character prefix for public keys, like `+` or `@`, but I thought that it would be better to start with something verbose and then introduce shortcuts if the verbose version is too annoying.

Support public key literals and tidy up handling of Raw vs PodId

---

src/backends/plonky2/emptypod.rs
src/backends/plonky2/mainpod/mod.rs
src/backends/plonky2/mock/emptypod.rs
src/backends/plonky2/mock/mainpod.rs
src/backends/plonky2/mock/signedpod.rs
src/backends/plonky2/signedpod.rs
src/middleware/mod.rs

This patch introduces an automatic implementation of Pod::equals, so that it does not have to be manually implemented for each pod.

Automatically implement Pod::equals

---

src/backends/plonky2/mock/mainpod.rs
src/backends/plonky2/primitives/ec/curve.rs
src/backends/plonky2/primitives/ec/field.rs
src/backends/plonky2/primitives/ec/gates/curve.rs
src/backends/plonky2/primitives/merkletree/mod.rs
src/frontend/custom.rs
src/frontend/mod.rs

chore: minor error handling improvements

---

src/backends/plonky2/primitives/ec/schnorr.rs
src/backends/plonky2/signedpod.rs

- serialize the signer in base58 both as Value and as the signer embedded in the SignedPod json data field.
- Implement serialization/deserialization for Signature
Resolve #333

fix: consistently serialize signer

---

src/middleware/basetypes.rs

The motivation is that since some commits ago, the hex representation was changed from little-endian to big-endian, and when cropping the long strings of hex (hex representation of byte-arrays), the small values (224 bits or less) were being represented by `0x00000000...`, which is indistinguishable from the `0` value.
This commit updates this cropped representation to print the last characters of the string (the less signifcant bytes of the big-endian representation), so that for example for the integer `5` the representation would be `0x...00000005`.
More context at https://github.com/0xPARC/pod2/issues/337.

change Hash (and RawValue) hex-string representation to show the least-significant field element as big-endian hex string

---

src/frontend/serialization.rs

Adds simple accessor methods for serialized POD IDs.

Make serialized POD IDs available out-of-crate

---

.github/workflows/typos.toml
src/backends/plonky2/primitives/merkletree/circuit.rs
src/backends/plonky2/primitives/merkletree/error.rs
src/backends/plonky2/primitives/merkletree/mod.rs

- implement `tree.insert` method to add new leaves to the tree (till now we could only add leaves at tree initial creation, not after), which returns a proof of correct insertion (proof of correct *state transition*)
- implement verification of proofs of correct insertion of leaves
- implement circuit that verifies proofs of correct insertion
- fix graphviz method after endianness change
Update: thanks @ax0 for pointing out the [tampering proofs case](https://github.com/0xPARC/pod2/pull/344/commits/79a532e97bc4e63d465b0445469e576adf8d3ef6), which required adding the [check 5.3](https://github.com/0xPARC/pod2/pull/344/commits/2da2e8237b35b8d50e9a4dcbeefb2a0285a677d6).

MerkleTree insertion proofs

---

src/lang/grammar.pest
src/lang/mod.rs
src/lang/pretty_print.rs
src/lang/processor.rs

This implements the SecretKey literal in Podlang, as follows:
```
SecretKey(base_64_encoded_string)
```
This follows the base64 encoding used for serialization of SecretKeys.

Secret keys in Podlang

---

Cargo.toml
src/backends/plonky2/mainpod/mod.rs
src/backends/plonky2/serialization.rs

Add the missing gates and generator in the serializer that were added with the PublicKeyOf operation.
Add a test for CircuitData serialization+deserialization to avoid these kind of bugs in the future.

fix: missing gate and generator for serialization

---

src/lang/grammar.pest
src/lang/mod.rs
src/lang/pretty_print.rs
src/lang/processor.rs
src/middleware/mod.rs

Closes #351 
This adds support for a syntactic sugar SELF keyword.
I've simplified my original design, so that this is pure syntactic sugar that gets removed during parsing. It's simply a shortcut for writing out the full SELF keyword in hex.

Support SELF keyword in Podlang parser

---

examples/main_pod_points.rs
src/backends/plonky2/mainpod/mod.rs
src/backends/plonky2/mock/mainpod.rs
src/examples/mod.rs
src/frontend/custom.rs
src/frontend/mod.rs
src/frontend/pod_request.rs
src/frontend/serialization.rs

MainPodBuilder::prove takes an argument containing `params`, but the MainPodBuilder struct already has a `params` field. At best this is redundant, at worst there is the possibility of passing different `params` to the compiler than those that were used when building the operations in MainPodBuilder.
This PR removes the `params` argument and uses `self.params` instead.

Remove unnecessary 'params' argument to MainPodBuilder::prove

---

src/backends/plonky2/recursion/circuit.rs

The `pad_circuit` function is potentially useful outside of pod2.  In order for the function to be correct when called by external code, it needs to check whether the provided `CommonCircuitData` uses zk, rather than checking if pod2 is configured to use zk.
While testing, I encountered an unfortunate issue where the `num_gates` calculation underflowed and the program kept adding gates until my system ran out of memory.  I assume that the underflow won't happen now that the function checks if the circuit is zk.  But it seems like a good idea to check for underflow anyway.

pad_circuit: use config to determine zk and check for underflow

---

src/backends/plonky2/mainpod/mod.rs
src/backends/plonky2/mock/emptypod.rs
src/backends/plonky2/mock/mainpod.rs
src/frontend/mod.rs
src/frontend/serialization.rs
src/middleware/mod.rs
src/middleware/pod_deserialization.rs

I missed this changes in #394 
Renames a few instances of `id` from the old PodID to `sts_hash` (as in statements hash)

quickfix Rename some `id` to `sts_hash`

---

src/backends/plonky2/serialization.rs

Since introduction pods need to be able to serialize their verifier data, it will be useful for external crates to be able to construct an instance of `VerifierOnlyCircuitDataSerializer`.  I suppose there is not much harm in allowing the other serializers to be constructed as well.
I added the `#[repr(transparent)]` in case the user wants to convert a reference to a `VerifierOnlyCircuitData` into a reference to a `VerifierOnlyCircuitDataSerializer`.

allow downstream crates to instantiate *CircuitDataSerializer

---

src/cache/disk.rs
src/cache/mem.rs
src/cache/mod.rs
src/lib.rs

The cache is very useful for external libraries that have their own intro pods or wrapper circuits, so let's make it public.

make cache pub

---

src/backends/plonky2/primitives/ec/curve.rs
src/frontend/custom.rs

Container update operations were previously ignored by desugar. Desugar is used by Rob's solver, so we need to update it.

Add cases to desugar function for container update ops

---

src/middleware/custom.rs

This is useful for a verifier that wants to verify a MainPod that contains a custom predicate in a public statement without knowledge of how the custom predicate is defined.

Allow creation of opaque custom predicate batch
