0xPARC/pod2

- src/examples.md
> feat: add examples

- book/src/statements.md
This PR documents the native statements as discussed in #7.
> docs: add native statement table

- src/frontend/mod.rs
> Improve formatting of SignedPods: show keys as strings

- src/backends/plonky2/mock_signed.rs
- src/examples.rs
- src/examples/custom.rs
- src/frontend/custom.rs
- src/frontend/mod.rs
- src/frontend/operation.rs
- src/frontend/statement.rs
- src/middleware/custom.rs
- src/middleware/operation.rs
> chore: refactor custom deduction and frontend code

- src/backends/plonky2/basetypes.rs
- src/backends/plonky2/mock_main/mod.rs
- src/backends/plonky2/mock_main/operation.rs
- src/backends/plonky2/mock_main/statement.rs
- src/backends/plonky2/mock_signed.rs
- src/backends/plonky2/primitives/merkletree.rs
- src/examples.rs
- src/examples/custom.rs
- src/frontend/custom.rs
- src/frontend/mod.rs
- src/frontend/operation.rs
- src/frontend/statement.rs
- src/middleware/containers.rs
- src/middleware/custom.rs
- src/middleware/mod.rs
- src/middleware/operation.rs
- src/middleware/statement.rs
> chore: add statement and KV metadata to frontend PODs

- .github/workflows/tests.yml
- src/backends/plonky2/basetypes.rs
- src/backends/plonky2/primitives/mod.rs
- src/backends/plonky2/primitives/signature.rs
> implement proof-based signatures using plonky2 proofs

- src/backends/plonky2/primitives/merkletree.rs
This PR replaces the hash function used for leaves in the SMT implementation to mitigate leaf and branch collisions.
> chore(merkletree): replace leaf hash function

- src/backends/plonky2/mock_main/mod.rs
- src/backends/plonky2/primitives/merkletree.rs
- src/frontend/mod.rs
- src/middleware/operation.rs
Added a test.
Also, I wrapped check() so if it doesn't pass, it prints the problem
> Add test for merkle statements, and some debug prints to verify()

- src/backends/plonky2/common.rs
- src/backends/plonky2/main.rs
- src/backends/plonky2/mock_main/mod.rs
- src/backends/plonky2/mock_signed.rs
- src/backends/plonky2/mod.rs
- src/backends/plonky2/primitives/merkletree_circuit.rs
It includes a skeleton for the MainPod verification circuit in plonky2.
It's missing a few things, including tests.
Related to #149
> MainPod circuit skeleton

- Cargo.toml
- src/backends/plonky2/basetypes.rs
- src/backends/plonky2/mock_main/mod.rs
- src/backends/plonky2/mock_main/operation.rs
- src/backends/plonky2/mock_main/statement.rs
- src/backends/plonky2/mock_signed.rs
- src/examples.rs
- src/frontend/containers.rs
- src/frontend/mod.rs
- src/frontend/serialization.rs
- src/frontend/statement.rs
- src/middleware/custom.rs
- src/middleware/mod.rs
- src/middleware/operation.rs
- src/middleware/serialization.rs
- src/middleware/statement.rs
This code serializes Signed and Main Pods to JSON format.
Signed Pods are serialized as such:
```json
{
"entries": {
"_type": {
"Raw": "0000000000000001000000000000000000000000000000000000000000000000"
},
"age": {
"Int": "30"
},
"a_dict_containing_one_key": {
"Dictionary": {
"foo": {
"Int": "123"
},
"an_array_containing_three_ints": [
{
"Int": "1"
},
{
"Int": "2"
},
{
"Int": "3"
}
],
"a_set_containing_two_strings": {
"Set": [
[
"foo",
"bar"
],
"baz"
]
}
}
},
"_signer": {
"Raw": "261530c5f3a02f290ee9c59c09b641e86002ffe1dc7d2eaa735b31d3aad0f5b6"
},
"very_large_int": {
"Int": "1152921504606846976"
},
"name": "test"
},
"proof": "9e0f4514…_signed_by_292fa0f3…",
"pod_class": "Signed",
"pod_type": "Mock"
}
```
Some points of note:
- Arrays, booleans, and strings are serialized as their direct …
> Serialization of Signed and Main Pods

- Cargo.toml
- src/backends/plonky2/mock/mainpod/mod.rs
- src/backends/plonky2/mod.rs
- src/backends/plonky2/primitives/signature.rs
- src/backends/plonky2/signedpod.rs
- src/frontend/mod.rs
- src/frontend/serialization.rs
- src/middleware/mod.rs
Resolves #147, unblocks #157.
~Depends on merging #158 first (the *'organize files...'* commit is from the #158); or if preferred we can merge this PR (#160) directly, which includes the changes of #158, but at least they are more clean to review separately.~
> implement SignedPod (non-mock) using proof-based signatures

- src/backends/plonky2/circuits/common.rs
- src/backends/plonky2/circuits/mainpod.rs
- src/backends/plonky2/mainpod/statement.rs
- src/frontend/mod.rs
- src/middleware/operation.rs
- src/middleware/statement.rs
> chore: implement Gt and GtEq as syntactic sugar

- src/backends/plonky2/circuits/common.rs
- src/backends/plonky2/circuits/mainpod.rs
- src/frontend/mod.rs
- src/middleware/basetypes.rs
- src/middleware/operation.rs
- src/middleware/statement.rs
Resolves #212.
Depends on #216.
> feat: implement HashOf statement and operation

- src/backends/plonky2/circuits/common.rs
- src/backends/plonky2/circuits/mainpod.rs
Towards #210 and #213.
Depends on #217.
> feat(backend): implement more ops

- src/backends/plonky2/circuits/common.rs
- src/backends/plonky2/circuits/mainpod.rs
- src/backends/plonky2/circuits/signedpod.rs
- src/middleware/custom.rs
- src/middleware/operation.rs
- src/middleware/statement.rs
> add target types for custom predicates

- src/backends/plonky2/circuits/common.rs
- src/backends/plonky2/circuits/mainpod.rs
> feat(backend): implement gadgets for remaining ops

- src/backends/plonky2/mainpod/mod.rs
> Use id as public inputs in MainPod verify

- Cargo.toml
- src/backends/plonky2/circuits/mainpod.rs
- src/backends/plonky2/circuits/metrics.rs
- src/backends/plonky2/circuits/mod.rs
- src/backends/plonky2/circuits/signedpod.rs
- src/backends/plonky2/circuits/utils.rs
- src/backends/plonky2/mainpod/mod.rs
- src/backends/plonky2/primitives/merkletree/circuit.rs
- src/backends/plonky2/primitives/signature/circuit.rs
Add utility macros to record the number of gates per block of circuit code.  The number gates are only recorded when the feature `metrics` is enabled.  If the feature is disabled the macros do nothing (this is to avoid any performance penalty).
Initially I instrumented more blocks of circuit code but then I removed the instrumentation on those that take a very low number of gates (from 0 to 6).
Usage example:
```sh
cargo test --release --features metrics test_main_ethdos -- --nocapture
```
Some initial thoughts:
- The recursive verification takes a lot of gates, with 4k gates per plonky2 signature verification
- The arity in the parameters has significant implications in the number of gates: higher arity slightly increases the number of gates per component, but some of these components …
> add gate count metrics

- book/src/examples.md
> fix anchored keys syntax

- src/backends/plonky2/circuits/mainpod.rs
- src/backends/plonky2/mainpod/mod.rs
- src/backends/plonky2/primitives/merkletree/circuit.rs
- src/backends/plonky2/recursion/circuit.rs
- src/backends/plonky2/signedpod.rs
Add timing and gates measuring to a few missing places and update measuring names to be shorter.
This PR has the changes required to collect the results from https://github.com/0xPARC/pod2/issues/291
> better measuring

- Cargo.toml
- src/backends/plonky2/emptypod.rs
- src/backends/plonky2/recursion/circuit.rs
resolves #248, closes #252 (implements the described 'Option A')
> add zk config, enabled by a feature (on by default)

- src/backends/plonky2/mock/mainpod.rs
- src/backends/plonky2/mock/signedpod.rs
- src/backends/plonky2/signedpod.rs
- src/constants.rs
- src/lang/processor.rs
- src/lib.rs
- src/middleware/containers.rs
> resolve #273: remove global constant MAX_DEPTH, instead use the respective value from Params

- src/backends/plonky2/primitives/merkletree/circuit.rs
- src/backends/plonky2/primitives/merkletree/error.rs
- src/backends/plonky2/primitives/merkletree/mod.rs
> feat(backend): add updates and deletions to Merkle tree state transition proofs
